"use client";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { ASPECTS, CATEGORIES, CATEGORY_LABELS, type Category } from "@/lib/works";

type WorkInput = { id?: string; title: string; slug: string; category: string; description: string; client: string | null; role: string | null; software: string; year: number; aspect: string; coverImage: string; coverBlur: string | null; previewClip: string | null; videoUrl: string | null; externalUrl: string | null; featured: boolean; published: boolean; sortOrder: number };
const blank: WorkInput = { title: "", slug: "", category: "MUSIC_VIDEO", description: "", client: "", role: "", software: "", year: new Date().getFullYear(), aspect: "16:9", coverImage: "", coverBlur: null, previewClip: null, videoUrl: null, externalUrl: null, featured: false, published: false, sortOrder: 99 };

export default function WorkEditor({ work }: { work?: WorkInput }) {
  const [data, setData] = useState(work ?? blank); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const router = useRouter();
  const set = (key: keyof WorkInput, value: unknown) => setData((current) => ({ ...current, [key]: value }));
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(""); const res = await fetch(data.id ? `/api/works/${data.id}` : "/api/works", { method: data.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data) }); const body = await res.json(); setBusy(false); if (!res.ok) return setMessage(body.error || "Save failed"); if (!data.id) router.replace(`/admin/works/${body.id}`); else setMessage("Saved."); router.refresh(); }
  async function upload(file: File) { setBusy(true); setMessage("Processing video…"); const form = new FormData(); form.append("file", file); const res = await fetch("/api/upload", { method: "POST", body: form }); const body = await res.json(); setBusy(false); if (!res.ok) return setMessage(body.error || "Upload failed"); setData((current) => ({ ...current, ...body, ...(body.url ? { coverImage: body.url, coverBlur: body.blur } : {}) })); setMessage(body.kind === "video" ? "Preview, cover and blur generated. Save to keep changes." : "Image ready. Save to keep changes."); }
  const field = (label: string, key: keyof WorkInput, type = "text") => <label className="block"><span className="mono-label mb-2 block text-mut">{label}</span><input type={type} value={String(data[key] ?? "")} onChange={(e) => set(key, type === "number" ? Number(e.target.value) : e.target.value)} className="admin-input" /></label>;
  return <form onSubmit={save} className="grid gap-10 md:grid-cols-12"><div className="space-y-6 md:col-span-7"><div className="grid gap-5 md:grid-cols-2">{field("Title", "title")}{field("Slug", "slug")}</div><label className="block"><span className="mono-label mb-2 block text-mut">Description</span><textarea value={data.description} onChange={(e) => set("description", e.target.value)} rows={5} className="admin-input resize-y" /></label><div className="grid gap-5 md:grid-cols-2">{field("Client", "client")}{field("Role", "role")}{field("Software", "software")}{field("Year", "year", "number")}</div><div className="grid gap-5 md:grid-cols-2"><label><span className="mono-label mb-2 block text-mut">Category</span><select value={data.category} onChange={(e) => set("category", e.target.value)} className="admin-input">{CATEGORIES.map((c) => <option key={c} value={c}>{CATEGORY_LABELS[c as Category]}</option>)}</select></label><label><span className="mono-label mb-2 block text-mut">Aspect</span><select value={data.aspect} onChange={(e) => set("aspect", e.target.value)} className="admin-input">{ASPECTS.map((a) => <option key={a}>{a}</option>)}</select></label></div>{field("External Vimeo / YouTube URL", "externalUrl")}</div><aside className="space-y-6 md:col-span-4 md:col-start-9"><div className="relative aspect-[4/3] overflow-hidden border border-line bg-panel">{data.coverImage ? <Image src={data.coverImage} alt="Cover preview" fill className="object-contain" /> : <div className="flex h-full items-center justify-center mono-label text-mut">No media</div>}</div><label className="flex min-h-28 cursor-pointer items-center justify-center border border-dashed border-mut px-6 text-center mono-label text-mut hover:text-fg">Drop / select full video or cover<input type="file" accept="video/mp4,video/quicktime,video/webm,image/jpeg,image/png,image/webp" className="sr-only" onChange={(e) => e.target.files?.[0] && upload(e.target.files[0])} /></label><div className="space-y-3"><label className="flex items-center justify-between border-b border-line py-3 mono-label">Published<input type="checkbox" checked={data.published} onChange={(e) => set("published", e.target.checked)} /></label><label className="flex items-center justify-between border-b border-line py-3 mono-label">Featured<input type="checkbox" checked={data.featured} onChange={(e) => set("featured", e.target.checked)} /></label></div>{message && <p className="text-sm text-mut">{message}</p>}<button disabled={busy} className="w-full bg-fg px-4 py-4 mono-label text-bg disabled:opacity-50">{busy ? "Working…" : "Save project"}</button>{data.id && <button type="button" onClick={async () => { if (!confirm("Delete this project?")) return; await fetch(`/api/works/${data.id}`, { method: "DELETE" }); router.replace("/admin/works"); router.refresh(); }} className="w-full border border-line px-4 py-3 mono-label text-mut">Delete</button>}</aside></form>;
}
